### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by j0ach1mmall3** [TheLightMC/PocketServer#16]
How will data such as player inventories and chunks etc be stored? Just wondering...

**Comment by nickrobson** [comment]
I'd assume that level data will be stored in LevelDB format (since that is what Vanilla uses and thus no conversions will be needed for sending the data).

I imagine items will be stored in a NBT-like format.

**Comment by j0ach1mmall3** [comment]
I see, thanks for explaining

**Comment by Fireflies** [comment]
Nick is correct, we'll be using the LevelDB format.
