### ISSUE TITLE
PluginLoader incompatible with PlugMan style plugins.

### ISSUE THREAD

**Issue by Fireflies** [TheLightMC/PocketServer#6]
From #5 
>**nickrobson**
>My code is beautiful. Have you even seen PluginLoader?!
>https://github.com/TheLightMC/PocketServer/blob/master/api/src/main/java/com/pocketserver/plugin/PluginLoader.java

I can't speak for other people but I commonly shade modules that vary in language level. Because of how the loader is setup it appears it's possible to have multiple `Plugin` descendants in a single JAR - this itself is not problematic but how it is implemented is. Some people may create modules that shade `Plugin` descendants that user a higher language level than what the server is running, due to how the `PluginLoader` works it will unload all the plugins found in a JAR if a single incompatible descendant is found.

**Comment by nickrobson** [comment]
Personally I think it's better to not load any classes inside the file if there are any classes with a lower language level than what can physically be run. This way there aren't any NoClassDefFoundErrors and no CNFEs where there would be none on a more recent version of Java.

**Comment by nickrobson** [comment]
@Fireflies Please see my edit above to see my outlook on this.

**Comment by Fireflies** [comment]
I totally agree with you on the "be defensive" part. Moving onto another possble issue; how will multiple plugins be handled if say somebody writes a PlugMan style plugin to essentially enable hotswapping of plugins? I think it's worth making only one plugin loadable from a JAR really.

**Comment by Fireflies** [comment]
Whoops. 😅

**Comment by nickrobson** [comment]
This'll need brainstorming. Another thing that is needed is the ability to load/unload/enable/disable/reload plugins while the server is running, which shouldn't be too hard, but it shall be interesting.

**Comment by Fireflies** [comment]
Latest plugin management updates make hotswapping of plugins a possibility.
